Allowing the system to check that the date of birth on the SA ID number is correct
praekeltfoundation/go-jsbox-malaria24 pull request #66
Opened 2018-01-11 14:33 UTC by sewagodimo

2018-01-11 16:13 UTC, miltontony requested changes
The changes look good, just some style fixes here and there 🍰

2018-01-11 16:13 UTC, miltontony commented on go-app.js
> +            var month,day,year;
You can declare these variables inline with the assignment
```javascript
var year = parseInt(id.substr(0,2));
```

2018-01-11 16:13 UTC, miltontony commented on go-app.js
> +            month =parseInt( id.substr(2,2));
please watch your spacing and be consistent. `var month = parseInt(id.substr(2,2));` is better.

2018-01-11 16:13 UTC, miltontony commented on test/app.test.js
> +            it('should make a valid Ona API call1', function () {
typo?

2018-01-11 16:13 UTC, miltontony commented on test/app.test.js
> +                    .input('9602294800085')
What's the significance of changing this? If it serves no purpose, you can just leave it as is.

2018-01-11 16:13 UTC, miltontony commented on test/app.test.js
> +            date_of_birth: '1980-02-21',
Do these dates need to change? Can't we just leave them as is?

2018-01-12 11:49 UTC, miltontony commented on go-app.js
> +        if( ('' + sum).slice(-1) == check){
Any reason why there's a space between the first 2 brackets?

2018-01-12 11:49 UTC, miltontony commented on go-app.js
> +            var month = parseInt( id.substr(2,2));
similarly here - please remove the space after the brackets

2018-01-15 08:57 UTC, sewagodimo commented
@miltontony fixed the formatting errors and ran the test on them

2018-01-15 09:12 UTC, miltontony approved these changes
👍 🍰 wtih

2018-01-15 10:41 UTC, merged